# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zfYsmUqtJfEzskTVZoNjK_Oca16PdMJ0
"""

# Import necessary libraries
import streamlit as st
from ecosnap_camera import eco_snap_camera
from ai_analyzer import ai_analyzer
from co2_estimator import co2_estimator
from csr_dashboard import csr_dashboard
from reward_center import reward_center
from personal_dashboard import personal_dashboard
from leaderboard import leaderboard
from streak_tracker import streak_tracker

# Main application layout
def main():
    st.sidebar.title("Navigation")
    app_mode = st.sidebar.selectbox("Choose a feature", [
        "EcoSnap Camera",
        "AI Analyzer",
        "CO₂ Estimator",
        "CSR Dashboard",
        "Reward Center",
        "Personal Dashboard",
        "Leaderboard",
        "Streak Tracker"
    ])

    if app_mode == "EcoSnap Camera":
        eco_snap_camera()
    elif app_mode == "AI Analyzer":
        ai_analyzer()
    elif app_mode == "CO₂ Estimator":
        co2_estimator()
    elif app_mode == "CSR Dashboard":
        csr_dashboard()
    elif app_mode == "Reward Center":
        reward_center()
    elif app_mode == "Personal Dashboard":
        personal_dashboard()
    elif app_mode == "Leaderboard":
        leaderboard()
    elif app_mode == "Streak Tracker":
        streak_tracker()

if __name__ == "__main__":
    main()

